### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by classicoman2** [carlos-canovas/P5.2-Bootstrap_Collaborative_Project#15]
Missing responsive menu. 
Remember that you have to create it using the [hamburguer button](https://en.wikipedia.org/wiki/Hamburger_button) to toggle it.

**Comment by adriangarcia2** [comment]
The responsive menu was there if you click this button ![Icon](https://i.ibb.co/j3Bgnz6/image.png).
Now we update with the correct button menu image.

**Comment by adriangarcia2** [comment]
Probably the problem was the JQ don't load as fast as need for put event on the button when load...
#17 We will work on that...
